# Generated by Django 4.2.30 on 2026-09-29 23:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import monitoreo.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Borrado Lógico')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre del Dispositivo')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Serie / Código')),
                ('nominal_power_kw', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Potencia Nominal (kW)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('MAINTENANCE', 'En Mantenimiento'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=20, verbose_name='Estado Operativo')),
                ('image', models.ImageField(blank=True, help_text='Formatos: .jpg, .png, .webp. Máximo 2 MB.', null=True, upload_to='devices/', validators=[monitoreo.validators.validate_image_file], verbose_name='Fotografía o Ficha Técnica')),
                ('installation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Instalación')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Borrado Lógico')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_critical', models.BooleanField(default=False, help_text='Define si la categoría requiere atención prioritaria ante fallas.', verbose_name='¿Es Crítica?')),
            ],
            options={
                'verbose_name': 'Categoría de Dispositivo',
                'verbose_name_plural': 'Categorías de Dispositivos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Borrado Lógico')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Organización')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='RUT / ID Tributario')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección Comercial')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Borrado Lógico')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Proveedor')),
                ('contact_person', models.CharField(max_length=120, verbose_name='Persona de Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Email del Proveedor')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('contract_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Contrato / Convenio')),
            ],
            options={
                'verbose_name': 'Proveedor de Equipos',
                'verbose_name_plural': 'Proveedores de Equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Borrado Lógico')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre de la Zona')),
                ('monthly_limit_kwh', models.DecimalField(decimal_places=2, help_text='Umbral máximo permitido antes de disparar alertas de consumo.', max_digits=12, verbose_name='Límite Mensual (kWh)')),
                ('floor_area_sqm', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, verbose_name='Superficie (m²)')),
                ('responsible_person', models.CharField(blank=True, max_length=120, verbose_name='Responsable de Área')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Zona Operativa?')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='monitoreo.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Borrado Lógico')),
                ('title', models.CharField(max_length=150, verbose_name='Título de la Orden')),
                ('scheduled_date', models.DateField(verbose_name='Fecha Programada')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado de la Orden')),
                ('technician_notes', models.TextField(blank=True, verbose_name='Notas del Técnico')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo de Intervención (CLP)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_orders', to='monitoreo.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Orden de Mantenimiento',
                'verbose_name_plural': 'Órdenes de Mantenimiento',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='EnergyTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Borrado Lógico')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Tarifa')),
                ('cost_per_kwh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Base por kWh (CLP)')),
                ('peak_cost_per_kwh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Horario Punta (CLP)')),
                ('currency', models.CharField(default='CLP', max_length=10, verbose_name='Moneda')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Tarifa Vigente?')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='monitoreo.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Tarifa Energética',
                'verbose_name_plural': 'Tarifas Energéticas',
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EnergyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Borrado Lógico')),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Detección')),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20, verbose_name='Nivel de Severidad')),
                ('message', models.TextField(verbose_name='Mensaje de la Alerta')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='¿Resuelta?')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoreo.device', verbose_name='Dispositivo Afectado')),
            ],
            options={
                'verbose_name': 'Alerta de Consumo',
                'verbose_name_plural': 'Alertas de Consumo',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='monitoreo.devicecategory', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='device',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='monitoreo.supplier', verbose_name='Proveedor Asociado'),
        ),
        migrations.AddField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='monitoreo.zone', verbose_name='Zona Asignada'),
        ),
        migrations.CreateModel(
            name='ConsumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Borrado Lógico')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Medición')),
                ('consumption_kwh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo Eléctrico (kWh)')),
                ('average_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Voltaje Promedio (V)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observaciones Operacionales')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_records', to='monitoreo.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Registro de Consumo',
                'verbose_name_plural': 'Registros de Consumo',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyZoneBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Borrado Lógico')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('month', models.PositiveIntegerField(verbose_name='Mes (1-12)')),
                ('budgeted_kwh', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Presupuesto Mensual (kWh)')),
                ('actual_kwh', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Consumo Real Acumulado (kWh)')),
                ('is_closed', models.BooleanField(default=False, verbose_name='¿Mes Cerrado?')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='monitoreo.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Presupuesto Mensual de Zona',
                'verbose_name_plural': 'Presupuestos Mensuales de Zonas',
                'ordering': ['-year', '-month'],
                'unique_together': {('zone', 'year', 'month')},
            },
        ),
    ]
