# Generated by Django 4.2.30 on 2026-09-29 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('es_critica', models.BooleanField(default=False, help_text='Indica si los equipos de esta categoría requieren monitoreo prioritario.', verbose_name='¿Categoría Crítica?')),
            ],
            options={
                'verbose_name': 'Categoría de Dispositivo',
                'verbose_name_plural': 'Categorías de Dispositivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre del Dispositivo')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True, verbose_name='Código de Inventario')),
                ('potencia_nominal_kw', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Potencia Nominal (kW)')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='Estado Operativo')),
                ('fecha_instalacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Instalación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='monitoreo.categoriadispositivo', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Organización')),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='RUT / Identificador')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre de la Zona')),
                ('limite_kwh', models.DecimalField(decimal_places=2, help_text='Umbral máximo mensual permitido antes de generar alertas.', max_digits=10, verbose_name='Límite Consumo (kWh)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la Zona')),
                ('responsable', models.CharField(blank=True, max_length=120, verbose_name='Responsable')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Zona Operativa?')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='monitoreo.organizacion', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['organizacion__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Medición')),
                ('consumo_kwh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo Registrado (kWh)')),
                ('voltaje_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Voltaje Promedio (V)')),
                ('observacion', models.CharField(blank=True, max_length=255, verbose_name='Observación Operativa')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_consumo', to='monitoreo.dispositivo', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Registro de Consumo',
                'verbose_name_plural': 'Registros de Consumo',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN_GLOBAL', 'Administrador Global'), ('ADMIN_ORG', 'Administrador de Organización'), ('OPERADOR', 'Operador de Monitoreo')], default='OPERADOR', max_length=30, verbose_name='Rol en el Sistema')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono de Contacto')),
                ('organizacion', models.ForeignKey(blank=True, help_text='Organización para scoping. Dejar en blanco si es Administrador Global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_perfil', to='monitoreo.organizacion', verbose_name='Organización Asignada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='monitoreo.zona', verbose_name='Zona'),
        ),
        migrations.CreateModel(
            name='AlertaConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de la Alerta')),
                ('nivel', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20, verbose_name='Nivel de Severidad')),
                ('mensaje', models.TextField(verbose_name='Detalle de la Alerta')),
                ('resuelta', models.BooleanField(default=False, verbose_name='¿Resuelta?')),
                ('resuelta_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Resolución')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='monitoreo.dispositivo', verbose_name='Dispositivo Afectado')),
            ],
            options={
                'verbose_name': 'Alerta de Consumo',
                'verbose_name_plural': 'Alertas de Consumo',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
